import type { Metadata } from "next";
// 1. Import your two new fonts
import { Concert_One, Pixelify_Sans } from "next/font/google";
import "./globals.css";

// 2. Set up Concert One as the body/sans font
const concertOne = Concert_One({
  variable: "--font-sans", // Use --font-sans for the default
  subsets: ["latin"],
  weight: "400", // This font only has one weight
});

// 3. Set up Pixelify Sans as the header font
const pixelifySans = Pixelify_Sans({
  variable: "--font-header", // Use a custom --font-header variable
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 4. Apply the new variables to the body */}
      <body
        className={`${concertOne.variable} ${pixelifySans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}